---
- name: Allow an instance to consume customOptions
  hosts: "{{ morpheus['instance']['name'] + '.' + morpheus['instance']['domainName'] }}"
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instance: "{{ morpheus['instance'] }}"
    decision: "{{ morpheus['customOptions']['decision'] }}"                               # SELECT input with OptionList: [{name: "Yes", value: true}, {name: "No", value: false}]
  tasks:
    - name: Print instance
      debug:
        msg: "{{ instance }}"
      register: instanceVariable

    - name: Print instance custom options
      debug:
        msg: "{{ morpheus['instance']['customOptions'] }}"
      register: instanceCustomOptions
    
    - name: Print decision
      debug:
        msg: "{{ decision }}"
      register: decisionResult

    - name: DEBUG INFORMATION
      debug:
        msg:
          - "Instance Variable: {{ instanceVariable }}"
          - "Instance Custom Options: {{ instanceCustomOptions }}"
          - "Decision: {{ decisionResult }}"
## OUTPUT IN COMMIT # 
