- name:  Retrieve JSON from Cypher
  hosts: uthman-6.0.6-test.localdomain
  gather_facts: false
  tasks:
     tasks:
      - name: Process JSON
        debug:
        msg: {{ lookup('cypher','secret=secret/jsontest') | to_json }}
