- name: JSON Processor via Cypher
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Good JSON
    debug:
      msg: "Good JSON is {{ lookup('cypher','secret=secret/jsontestgoodjson') }}"
    register: goodJSON
  - name: Bad JSON
    debug:
      msg: "Bad JSON is {{ lookup('cypher','secret=secret/jsontest') }}"
    register: badJSON

  - debug:
      var: goodJSON
