- name: Retrieve a Cypher using an Ansible playbook 
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"          # generic to allow this playbook to be ran on a specific host
                                                                                                      # constructed by concatenating the properties referenced e.g. uthman-test.local
  vars:
    ansible_python_interpreter: /usr/bin/python2
    cypher_result: "{{ lookup('cypher','secret=secret/test') }}"
  tasks:
  - name: Cypher response JSON
    debug:
      msg: "Cypher result is {{ cypher_result }}"
    register: cypherResult
  - debug:
      var: cypherResult
