- name:  Retrieve JSON from Cypher
  hosts: uthman-6.0.6-test.localdomain
  gather_facts: false
  tasks:
     tasks:
      - name: Process JSON
        debug:
          msg: "This is the JSON processed: " + "{{ lookup('cypher','secret=secret/jsontest') }}"
