- name:  Cypher lookup tests
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
   - name: get user login
     ansible.builtin.set_fact:
        username1: "{{ lookup('cypher','secret=secret/ueqbal/test') }}"
  #      username2: "{{ lookup('cypher','secret=secret/ueqbal') }}"             # "An unhandled exception occurred while running the lookup plugin 'cypher'. Error was a <class 'simplejson.errors.JSONDecodeError'>, original message: Expecting value: line 1 column 2 (char 1)"
        username3: "{{ lookup('cypher','secret=secret/ueqbal/') }}"             # "An unhandled exception occurred while running the lookup plugin 'cypher'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The secret secret/ueqbal/ doesn't seem to exist for cypher lookup"

   - name: secret/ueqbal/test
     ansible.builtin.debug:
        var: username1
#   - name: secret/ueqbal
#     ansible.builtin.debug:
#        var: username2
   - name: secret/ueqbal/
     ansible.builtin.debug:
        var: username3


# Assumption is that you have two Cypher Access Policies (https://docs.morpheusdata.com/en/latest/getting_started/guides/cypher_policies.html#cypher-access-policies) in place: 
# Policy 1: 
# {
#   "policy": {
#     "policyType": {
#       "code": "cypher"
#     },
#     "config": {
#       "keyPattern": ".*",
#       "read": false,
#       "write": false,
#       "update": false,
#       "delete": false,
#       "list": false
#     },
#     "enabled": true,
#     "refType": "Role",
#     "refId": "<scoped-role-id-here>",
#     "eachUser": false,
#     "name": "Policy 1"
#   }
# }
#
# Policy 2: 
# {
#   "policy": {
#     "policyType": {
#       "code": "cypher"
#     },
#     "config": {
#       "keyPattern": "secret/ueqbal/.*",
#       "read": true,
#       "write": false,
#       "update": false,
#       "delete": false,
#       "list": true
#     },
#     "enabled": true,
#     "refType": "Role",
#     "refId": "<scoped-role-id-here>",
#     "eachUser": false,
#     "name": "Policy 2"
#   }
# }
