- name:  Lookup cypher test
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
   - name: get user login
     ansible.builtin.set_fact:
        username: "{{ lookup('cypher','secret=secret/ueqbal') }}"
 
   - name: Debug cypher lookup
     ansible.builtin.debug:
        var: username
