- name:  Retrieve JSON from Cypher
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars: 
    json_data: "{{ lookup('cypher','secret=secret/jsontestgoodjson') }}"
  tasks:
  - name: Process JSON
    debug:
      msg: 'This is the JSON processed: {{ json_data.json }}'
    register: jsonOutput
  
  - name: Debug Bad JSON
    debug:
      var: jsonOutput
