- name:  Retrieve JSON from Cypher
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars: 
    badJSON: `{{ lookup('cypher','secret=secret/jsontestgoodjson') }}`
  tasks:
  - name: Process JSON
    debug:
      msg: 'This is the JSON processed: {{ badJSON }}'
    register: jsonOutput
  
  - name: Debug Bad JSON
    debug:
      var: jsonOutput
