- name:  Retrieve JSON from Cypher
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars: 
    json_data: "{{ lookup('cypher','secret=secret/jsontest') }}"
  tasks:
  - name: Process JSON
    debug:
      msg: 'This is the JSON data: {{ json_data }}'
    register: jsonData
  
  - name: Process JSON
    debug:
      msg: 'This is the JSON processed: {{ json_data.json.colours }}'
    register: jsonOutput
  
  - name: Debug Bad JSON
    debug:
      var: json_data
