---
- name: "Fetch Morpheus API Token from Ansible Vault and Call /api/whoami"
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  gather_facts: yes
  become: true
  become_user: ueqbal
  vars:
    morpheus_url: "ueqbal-morph-appliance.localdomain"
    api_endpoint: "/api/whoami"
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - /opt/morpheus/.local/morpheus_api_credentials.yml  
  tasks:
    - name: "[0] - [DEBUG] - Print Decrypted API Token"
      debug:
        msg: "Decrypted API token: {{ api_token }}"
        
    - name: "[1] - [Task] - Simple Google GET"
      shell: |
        curl -vvv https://www.google.com
      register: google_response
      
    - name: "[2] - [Task] - Call Morpheus /api/whoami to verify token"
      shell: |
        curl -k -H "Authorization: Bearer {{ api_token }}" "https://{{ morpheus_url }}{{ api_endpoint }}" -vvv
      register: whoami_response

    - name: "[1] - [DEBUG] - Check Google GET response"
      debug:
        var: google_response
        
    - name: "[2] - [DEBUG] - Display /api/whoami response"
      debug:
        var: whoami_response
    
