---
- name: Install nvm
  hosts: ueqbal-linux.infoblox.den.morpheusdata.com
  become: true  
  become_user: ueqbal
  become_method: su
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: DEBIAN | INSTALL pip
      apt:
        name: python3-pip
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "Debian"

    - name: REDHAT | INSTALL pip
      yum:
        name: python3-pip
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "RedHat"

    - name: DEBIAN | INSTALL six MODULE 
      apt:
        name: python3-six
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "Debian"

    - name: REDHAT | INSTALL six MODULE 
      yum:
        name: python3-six
        state: present
      become: true
      become_user: root
      when: ansible_os_family == "RedHat"

    - name: CHECK CURRENT USER
      command: whoami
      register: current_user

    - name: DEBUG | CURRENT USER
      debug:
        msg: "Current user is {{ current_user.stdout }}"

    - name: DOWNLOAD AND INSTALL NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
      register: nvm_install_result
      when: nvm_version is not defined

    - name: DEBUG | NVM_INSTALL_RESULT
      debug:
        msg: "NVM installation result: {{ nvm_install_result.stdout }}"

    - name: SET EXECUTABLE PERMISSIONS ON nvm.sh 
      command: "chmod +x ~/.nvm/nvm.sh"
      register: chmod_nvm_result
    
    - name: CHECK PERMISSIONS ON nvm.sh 
      command: 'stat -c "%a" ~/.nvm/nvm.sh'
      register: nvm_sh_permissions_result
      
    - name: VERIFY NVM INSTALL
      shell: ~/.nvm/nvm.sh && nvm --version
      register: nvm_version
      when: nvm_sh_permissions_result == "775"

    - name: DEBUG | NVM_VERSION
      debug:
        msg: "NVM version installed: {{ nvm_version }}\r\nDEBUG: [current_user: {{ current_user }}, nvm_install_result: {{ nvm_install_result }}, chmod_nvm_result: {{ chmod_nvm_result }}, nvm_sh_permissions_result: {{ nvm_sh_permissions_result }}, nvm_version: {{ nvm_version }}]"
