---
- name: Install nvm for a specific user
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  become: yes
  become_user: ueqbal
  become_method: su
  tasks:
    - name: Check current user
      command: whoami
      register: current_user

    - name: Debug current user
      debug:
        msg: "Current user is {{ current_user.stdout }}"

    - name: Download and install nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
      register: nvm_install_result

    - name: Debug nvm installation result
      debug:
        msg: "NVM installation result: {{ nvm_install_result.stdout }}"

    - name: Verify nvm installation
      shell: |
        . ~/.nvm/nvm.sh && nvm --version
      args:
        executable: /bin/bash
      register: nvm_version

    - name: Debug nvm version
      debug:
        msg: "NVM version installed: {{ nvm_version.stdout }}"
