---
- name: Install nvm
  hosts: ueqbal-linux.infoblox.den.morpheusdata.com
  become: true  
  become_user: ueqbal
  become_method: su
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: DEBIAN | INSTALL pip
      apt:
        name: python3-pip
        state: present
      become_user: root
      when: ansible_os_family == "Debian"

    - name: REDHAT | INSTALL pip
      yum:
        name: python3-pip
        state: present
      become_user: root
      when: ansible_os_family == "RedHat"

    - name: DEBIAN | INSTALL six MODULE 
      apt:
        name: python3-six
        state: present
      become_user: root
      when: ansible_os_family == "Debian"

    - name: REDHAT | INSTALL six MODULE 
      yum:
        name: python3-six
        state: present
      become_user: root
      when: ansible_os_family == "RedHat"

    - name: CHECK CURRENT USER
      command: whoami
      register: current_user

    - name: DEBUG | CURRENT USER
      debug:
        msg: "Current user is {{ current_user.stdout }}"

    - name: DOWNLOAD AND INSTALL NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash
      register: nvm_install_result
      when: nvm_version is not defined

    - name: DEBUG | NVM_INSTALL_RESULT
      debug:
        msg: "NVM installation result: {{ nvm_install_result.stdout }}"

    - name: VERIFY NVM INSTALL
      command: ". ~/.nvm/nvm.sh && nvm --version"
      register: nvm_version

    - name: DEBUG | NVM_VERSION
      debug:
        msg: "NVM version installed: {{ nvm_version.stdout }}"
