---
- hosts: "{{ morpheus['instance']['containerDetails'][0]['externalFqdn'] }}"
  debugger: always
  tasks:
    - name: Ping test
      ansible.builtin.ping:
      register: PING_RESULT

    - name: Show Ping Result
      debug:
        var: PING_RESULT

    - name: Continuing
      debug:
        msg: "Continuing to next task..."
