---
- hosts: uthman-ubuntu-test-1.localdomain
  tasks:
    - name: Disable cloud-init
      ansible.builtin.file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
 
    - name: Reboot node and wait for it to restart
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300
        test_command: hostname
 
    - name: Output message
      debug:
        msg: "Next task"
