---
- hosts:
    - "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
    - name: Ping
      ansible.builtin.ping: null
    
    - name: Reboot node and wait for it to restart
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300
        connect_timeout: 30
        test_command: hostname
        post_reboot_delay: 30
