---
- hosts:
    - "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
    - name: Restart the instance...
      uri:
        url: "https://ueqbal-morph-appliance.localdomain/api/instances/{{ morpheus['instance']['id'] }}/restart"
        method: PUT
        headers:
          accept: application/json
          authorization: "Bearer + {{ morpheus['apiAccessToken'] }}"
        validate_certs: no
        return_content: yes
      register: result
    
    - name: Debug info from previous task
      ansible.builtin.debug:
        var: result
        verbosity: 2
