---
- hosts:
    - "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
    - name: Ping
      ansible.builtin.ping: null
    - name: Reboot the instance with the Ansible module...
      reboot:
        post_reboot_delay: 300
        test_command: morpheus-node-ctl status
      register: rebooted
    - name: Debug info from previous task
      ansible.builtin.debug:
        var: rebooted
        verbosity: 2
  handlers:
    - name: Wait for server to come back online...
      local_action:
        module: wait_for 
          host={{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }} 
          port=22 
          delay=10
        become: false
