---
- hosts:
    - "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  tasks:
    - name: Test sshd configuration and restart
      command: sshd -t
      notify: [ 'restart sshd' ]
    - name: Debug info from previous task
      ansible.builtin.debug:
        var: ssh-restarted
        verbosity: 3
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
      register: ssh-restarted
    - name: Wait for server to come back online...
      local_action:
        module: wait_for 
          host={{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }} 
          port=22 
          delay=10
        become: false
