---
- name:  
  hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars: 
    vcenter_hostname: "{{ lookup('cypher','secret=secret/vcenter_host') }}"
    vcenter_username: "{{ lookup('cypher','secret=secret/vcenter_username') }}"
    vcenter_password: "{{ lookup('cypher','secret=secret/vcenter_password') }}"
    datacenter_name: "{{ lookup('cypher','secret=secret/vcenter_datacenter') }}"
    guest_name: "{{ morpheus['instance']['name'] }}"
  tasks:
  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "/{{ datacenter_name }}/vm/"
      name: "{{ guest_name }}"
      state: present
      snapshot_name: snap1
      description: snapshot triggered from an Ansible playbook
    delegate_to: localhost
    register: snapshotResults
  - name: Debug snapshot results
    debug:
      var: snapshotResults
  - name: Test sshd configuration and restart
      command: sshd -t
      notify: [ 'restart ssh' ]
    - name: Debug info from previous task
      ansible.builtin.debug:
        var: ssh-restarted
        verbosity: 3
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
