- name:  Windows Updates
  hosts: uthman-windows-3.localdomain
  gather_facts: false
  tasks:
    - name: Running Security, Critical, and Update Rollups
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups']
        reboot: false
    - name: Check that the Morpheus Windows Agent is running
      ansible.windows.win_reboot:
          test_command: 'exit (Get-Service -Name "Morpheus Windows Agent").Status -ne "Running"'

# ['Updates', 'DefinitionUpdates', 'DeveloperKits', 'FeaturePacks', 'Connectors', 'Application', 'Guidance', 'ServicePacks', 'Tools' ]
