- hosts: "{{ morpheus['instance']['hostname'] + '.' + morpheus['instance']['domainName'] }}"
  vars:
    print_morpheus_user: "{{ morpheus['user'] }}"
  tasks:
    - name: '[1] ping localhost'
      ping:
      register: ping_result

    - name: '[2] ping_result'
      debug:
        var: ping_result
        verbosity: 3

    - name: '[3] morpheus user'
      debug:
        var: print_morpheus_user
        verbosity: 3
